package com.alzheimer.backend.medical;

public enum EventType {
    RECORD_CREATED,
    RECORD_UPDATED,
    MEDICAL_RECORD_UPDATED,
    RISK_FACTOR_ADDED,
    RISK_FACTOR_UPDATED,
    RISK_FACTOR_REMOVED,
    PREVENTION_ACTION_ADDED,
    PREVENTION_ACTION_UPDATED,
    PREVENTION_ACTION_COMPLETED,
    PREVENTION_ACTION_CANCELLED,
    RISK_SCORE_UPDATED,
    RECOMMENDATION_GENERATED
}
